sonar.projectKey=Bayly-AI_AgentGuard2
sonar.organization=bayly-ai
sonar.projectName=AgentGuard
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,docker/**,.github/**,docs/**
sonar.cpd.exclusions=**
